name = "Femshop2"
uuid = "c5e326e7-9e2a-46bd-bc5c-a950ccb14015"
authors = ["Aadesh", "Eric", "Hari"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
